general/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views
# from custom_functions import calculator,export_csv

urlpatterns = [
            url(r'^$', views.homepage, name='homepage'),
            url(r'^signup/Page/$', views.register,  name="register"),
            url(r'^login/Page/$', views.user_login,  name="login"),
            url(r'^user-logout/$', views.user_logout,  name="logout"),
            url(r'^admin-page/$', views.admin,  name="admin"),
            url(r'^all-orders/$',views.all_orders, name = "all_orders"),
            url(r'^all-payments/$',views.all_payments, name = "all_payments"),
            url(r'^add-item/$',views.add_item, name = "add_item"),
            url(r'^new-category/$',views.add_category, name = "add_category"),
            url(r'^delete-item/(?P<pk>[-\w]+)/$',views.delete_item, name = "delete_item"),
            url(r'^get-item/$',views.getItem, name = "get_item"),
            url(r'^edit-item/$',views.edit_item, name = "edit_item"),
            url(r'^shoppingCart/$',views.view_cart, name = "view_cart"),
            # url(r'^categoryLive/(?P<value>.+)$',views.getLiveCategory, name = "getLiveCategory"),
            # url(r'^categoryPassed/(?P<value>.+)$',views.getPassedCategory, name = "getPassedCategory"),
            url(r'^confirm-order/$',views.get_confirmation_order, name = "get_confirmation_order"),
            # url(r'^Contact-us/$',views.contact, name = "contact"),
            url(r'^customer-list/$',views.all_customers, name = "all_customers"),
            url(r'^customer-payment-list/$',views.customer_payments, name = "all_customers_payments"),
            # url(r'^userComment/$',views.user_comment, name = "user_comment"),
            # url(r'^search-results/(?P<action>[-\w]+)/$',views.user_search, name = "user_search"),
            url(r'^remove-from-cart/(?P<item_pk>[-\w]+)/$',views.remove_from_cart, name = "remove_from_cart"),
            url(r'cart-box/$',views.cart_box, name = "cart_box"),
            url(r'^items/(?P<category>[-\w]+)/$',views.allStoreItems, name = "all-items"),
            url(r'^details/(?P<slug>[-\w]+)/(?P<pk>.+)/$',views.itemDetails, name = "item_details"),
            url(r'^storeitems/(?P<category>[-\w]+)/(?P<subcategory>[-\w]+)/$',views.storeItems, name = "store-items"),
            url(r'invoice/(?P<tracking_id>.+)/$', views.package_invoice_page, name="package_invoice"),
            # url(r'^calculator/$', calculator, name ="calculator"),
            # url(r'^export/csv/$', export_csv, name='export_csv'),
            # url(r'^staff-login-access/$', views.staff_login_access, name="staff_login_access"),
            url(r'^customer-orders/$', views.customer_orders, name="all_customer_orders"),
            url(r'^packages/$', views.customer_packages, name="all_customer_packages"),
            # url(r'^vendor/play/$', views.get_play_event, name="get_play_event"),   
            # url(r'^export/tradingDetails/(?P<useracc_obj>[-\w]+)/$', views.tradingDetails, name='tradingDetails'),
            # url(r'^closing/djp/$', views.close_djp_client, name="close_djp_client"),
            # pay-pal
            url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

            
]

lookFab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from general.views import homepage
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete



def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_co


urlpatterns = [

    
    url(r'^adminLookFab/', admin.site.urls),
    url(r'^', include("general.urls", namespace="general")),
    url(r'^payment', include("payment.urls", namespace="payments")),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^resetpassword/passwordsent/$', password_reset_done, name="password_reset_done"),
    url(r'^resetpassword/$', password_reset, name="password_reset"),
    # url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

payment/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views

urlpatterns = [
			url(r'^paystackpay/$',views.mainPay, name="mainPay"),
            url(r'^verify_payment/$', views.verify_payment, name='verify_payment'),
            # url(r'^signup/Page/$', views.register,  name="register"),
            # url(r'^login/Page/$', views.user_login,  name="login"),
            # url(r'^user-logout/$', views.user_logout,  name="logout"),
            # url(r'^admin-page/$', views.admin,  name="admin"),
            # url(r'^all-orders/$',views.all_orders, name = "all_orders"),
            # url(r'^all-payments/$',views.all_payments, name = "all_payments"),
            # url(r'^add-item/$',views.add_item, name = "add_item"),
            # url(r'^new-category/$',views.add_category, name = "add_category"),
            # url(r'^delete-item/(?P<pk>[-\w]+)/$',views.delete_item, name = "delete_item"),
            # url(r'^get-item/$',views.getItem, name = "get_item"),
            # url(r'^edit-item/$',views.edit_item, name = "edit_item"),
            # url(r'^shoppingCart/$',views.view_cart, name = "view_cart"),
            # url(r'^categoryLive/(?P<value>.+)$',views.getLiveCategory, name = "getLiveCategory"),
            # url(r'^categoryPassed/(?P<value>.+)$',views.getPassedCategory, name = "getPassedCategory"),
            # url(r'^confirm-order/$',views.get_confirmation_order, name = "get_confirmation_order"),
            # url(r'^Contact-us/$',views.contact, name = "contact"),
            # url(r'^customer-list/$',views.all_customers, name = "all_customers"),
            # url(r'^userComment/$',views.user_comment, name = "user_comment"),
            # url(r'^search-results/(?P<action>[-\w]+)/$',views.user_search, name = "user_search"),
            # url(r'^remove-from-cart/(?P<item_pk>[-\w]+)/$',views.remove_from_cart, name = "remove_from_cart"),
            # url(r'cart-box/$',views.cart_box, name = "cart_box"),
            # url(r'^items/(?P<category>[-\w]+)/$',views.allStoreItems, name = "all-items"),
            # url(r'^details/(?P<slug>[-\w]+)/(?P<pk>.+)/$',views.itemDetails, name = "item_details"),
            # url(r'^storeitems/(?P<category>[-\w]+)/(?P<subcategory>[-\w]+)/$',views.storeItems, name = "store-items"),
            # url(r'invoice/(?P<tracking_id>.+)/$', views.package_invoice_page, name="package_invoice"),
            # url(r'^calculator/$', calculator, name ="calculator"),
            # url(r'^export/csv/$', export_csv, name='export_csv'),
            # url(r'^staff-login-access/$', views.staff_login_access, name="staff_login_access"),
            # url(r'^customer-orders/$', views.customer_orders, name="all_customer_orders"),
            # url(r'^packages/$', views.customer_packages, name="all_customer_packages"),
            # url(r'^vendor/play/$', views.get_play_event, name="get_play_event"),   
            # url(r'^export/tradingDetails/(?P<useracc_obj>[-\w]+)/$', views.tradingDetails, name='tradingDetails'),
            # url(r'^closing/djp/$', views.close_djp_client, name="close_djp_client"),
            # url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

            
]

general/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q, Sum
from django.utils import timezone
from django.conf import settings
import datetime
from django.utils import timezone
from django.template.defaultfilters import slugify
from general.modelchoices import *
import math

# Create your models here.


class CostSetting(models.Model):
    """ The stakeholders cost in percentage """
    dollar_exchange_rate = models.FloatField(default= 360.0)

    def __unicode__(self):
        return '%s' %(self.dollar_exchange_rate)


class UserAccount(models.Model):
    """ user details """
    user = models.OneToOneField(User, unique=True, null=True, blank=True)
    created_on = models.DateTimeField(default=timezone.now)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    profile_updated = models.BooleanField(default=False)


    class Meta:
	    verbose_name_plural = 'UserAccount'
	    ordering = ['-created_on']

    def __unicode__(self):
	    return '%s' %(self.user)

    def getItemsInCart(self):
		return self.orderitem_set.filter(ordered=False,deleted=False).count()

    def getUserPackages(self):
		return self.packages_set.filter(deleted=False).count()

    

class Item(models.Model):
	name                        = models.CharField(max_length=500, blank=True, null=True) 
	created_on                  = models.DateTimeField(default=timezone.now)
	courier_tracking_number     = models.CharField(max_length=500, blank=True, null=True)
	created_by                  = models.CharField(max_length=500, blank=True, null=True)
	description                 = models.CharField(max_length=500)
	quantity                    = models.IntegerField(default=1)
	quantity_left               = models.IntegerField(default=1)
	quantity_sold               = models.IntegerField(default=0)
	status                      = models.CharField(max_length=50, default="New")
	deleted                     = models.BooleanField(default=False)
	weight                      = models.FloatField(default= 1.0)
	link                        = models.CharField(max_length=500, null=True, blank=True)
	tag                         = models.CharField(max_length = 50, choices=CATEGORY, null=True)
	sub_category				= models.CharField(max_length = 50, choices=TAGS, null=True)
	archive                     = models.BooleanField(default=False)
	category                    = models.ForeignKey('Category' ,null=True,blank=True)
	price 						= models.IntegerField(default=1)
	slug 						= models.SlugField(max_length=500,unique=False,null=True,blank=True)
	shipping_cost_USA           = models.FloatField(default= 1.0)
	shipping_cost_NGN           = models.FloatField(default= 1.0)
	item_image_small            = models.ImageField(upload_to="item_photo", null=True, blank=True)
	item_image_big              = models.ImageField(upload_to="item_photo", null=True, blank=True)


	class Meta:
	    verbose_name_plural = 'Item'
	    ordering = ['-created_on']

	def __unicode__(self):
	    return '%s - %s - %s' %(self.name, self.category , self.price)


class Category(models.Model):
	category_name               = models.CharField(max_length=500, blank=True, null=True)
	created_on                  = models.DateTimeField(default=timezone.now)


	class Meta:
	    verbose_name_plural = 'Category'
	    ordering = ['-created_on']

	def __unicode__(self):
	    return '%s' %(self.category_name)



class Cart(models.Model):
	user_obj = models.ForeignKey(UserAccount,null=True,blank=True)
	order_placed = models.BooleanField(default=False)
	created_on = models.DateTimeField(default=timezone.now)


	class Meta:
	    verbose_name_plural = 'Cart'
	    ordering = ['-created_on']

	def __unicode__(self):
	    return '%s' %(self.user_obj.username)


class Packages(models.Model):
	tracking_number = models.CharField(max_length=50, blank=True, null=True)
	user = models.ForeignKey(UserAccount, null=True, blank=True)
	created_on = models.DateTimeField(default=timezone.now)
	status = models.CharField(max_length=50, default="New")
	payment_status = models.CharField(max_length=50, default="Pending")
	shipping_status = models.CharField(max_length=50, default="Pending")
	items_count = models.IntegerField(default=1)
	deleted = models.BooleanField(default=False)
	total_amount = models.FloatField(default= 1.0)
	shipping_destination = models.CharField(max_length=500, null=True, blank=True)
	shippingCost = models.FloatField(default= 1.0)
	subTotal = models.FloatField(default= 1.0)

	class Meta:
	    verbose_name_plural = 'Packages'
	    ordering = ['-created_on']

	def __unicode__(self):
	    return '%s' %(self.user.user.username)

	def items_in_package_count(self):
		return self.orderitem_set.filter(ordered=True,deleted=False).count()

	def items_in_package(self):
		return self.orderitem_set.filter(ordered=True,deleted=False)


class PackageInvoice(models.Model):
    user            = models.ForeignKey(UserAccount, null = True)
    created_on      = models.DateTimeField(default = timezone.now)
    invoice         = models.FileField(upload_to='shipping_package_invoices/%Y/%m/%d')
    package         = models.ForeignKey(Packages, null=True, blank=True)
    
    class Meta:
        verbose_name_plural  = "Shipping Package Invoice"

    def __unicode__(self):
        return self.package.tracking_number


class OrderItem(models.Model):
	user_obj 					= models.ForeignKey(UserAccount,null=True,blank=True)
	name                        = models.CharField(max_length=500, blank=True, null=True) 
	created_on                  = models.DateTimeField(default=timezone.now)
	courier_tracking_number     = models.CharField(max_length=500, blank=True, null=True)
	created_by                  = models.CharField(max_length=500, blank=True, null=True)
	quantity                    = models.IntegerField(default=1)
	status                      = models.CharField(max_length=50, default="New")
	deleted                     = models.BooleanField(default=False)
	link                        = models.CharField(max_length=500, null=True, blank=True)
	price 						= models.FloatField(default= 1.0)
	slug 						= models.SlugField(max_length=500,unique=False,null=True,blank=True)
	ordered                     = models.BooleanField(default=False)
	item_id                     = models.IntegerField(default=1)
	shipping_cost_USA           = models.FloatField(default= 1.0)
	shipping_cost_NGN           = models.FloatField(default= 1.0)
	item_image                  = models.ImageField(upload_to="order_photo", null=True, blank=True)
	package						= models.ForeignKey(Packages, null=True, blank=True)
	

	class Meta:
	    verbose_name_plural = 'OrderItem'
	    ordering = ['-created_on']

	def __unicode__(self):
	    return '%s' %(self.name)

	def getTotal(self):
		return float(self.price * self.quantity)

	def getShippingCost(self,ship_to):
		if ship_to == "USA":
			return float(self.quantity * self.shipping_cost_USA)
		else: 
			return float(self.quantity * self.shipping_cost_NGN)


class Payments(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField(max_length=15)
    status = models.CharField(max_length=50, blank=True, null=True, default="Pending")
    date_created = models.DateField(null=True, blank=True)
    payment_ref = models.CharField(max_length=50, blank=True, null=True)
    packageID = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
    	verbose_name_plural = 'Payments'
        ordering = ['-date']

    def __unicode__(self):
        return unicode(self.user)

general/forms.py
from django import forms
from django.contrib.auth.models import User
from general.models import UserAccount
from general.modelchoices import *
# from tinymce.models import HTMLField
from general.models import UserAccount, Category, Item



attrs3 = {'class': 'form-control', 'required': 'required'}

class DateInput(forms.DateInput):
    input_type = 'date'


class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ItemForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs=attrs3))
	description = forms.CharField(widget=forms.TextInput(attrs=attrs3))
	class Meta:
	    model = Item
	    fields = ('name', 
	    	'description', 
	    	'category', 
	    	'weight', 
	    	'tag', 
	    	'sub_category', 
	    	'quantity', 
	    	'price',
	    	'shipping_cost_USA',
	    	'shipping_cost_NGN',
	    	'item_image_small',
	    	'item_image_big',)


class CategoryForm(forms.ModelForm):

	category_name = forms.CharField(help_text="Category Name", required=True,
	                             widget=forms.TextInput(attrs={'required': 'required'}))

	class Meta:
	    model = Category
	    fields = ('category_name',)

general/templates/general/all_customer_packages.html
{% extends 'general/index.html' %}
{% load staticfiles %}
{% load humanize %}

{% block inner_content %}

	<!-- banner -->
	 
	<!-- //banner -->
    <!-- <div class="banner_bottom_agile_info">
	    <div class="container">
            <div class="banner_bottom_agile_info_inner_w3ls">
    	           <div class="col-md-6 wthree_banner_bottom_grid_three_left1 grid">
						<figure class="effect-roxy">
							<img src="{% static 'images/bottom1.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>
								<h3><span>F</span>all Ahead</h3>
								<p>New Arrivals</p>
							</figcaption>			
						</figure>
					</div>
					 <div class="col-md-6 wthree_banner_bottom_grid_three_left1 grid">
						<figure class="effect-roxy">
							<img src="{% static 'images/bottom2.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>
								<h3><span>F</span>all Ahead</h3>
								<p>New Arrivals</p>
							</figcaption>			
						</figure>
					</div>
					<div class="clearfix"></div>
		    </div> 
		 </div> 
    </div> -->
	<!-- schedule-bottom -->
	
	<!-- //schedule-bottom -->
  	<!-- banner-bootom-w3-agileits -->
	
<!-- /new_arrivals --> 
	<div class="new_arrivals_agile_w3ls_info">

		<div class="container">
			{% if orders_count %}
		    <h3 class="wthree_text_info"><span>Your packages</span></h3>
		    {% else %}
		    <h3 class="wthree_text_info"><span>Your have no packages presently</span></h3>
		    {% endif %}
				<div id="">				
					{% for item in order_items %}
					<div class="well">
						<div class="row">

							<div class="col-md-4">		
								<span><strong>User: </strong> {{item.user.user.username}}</span><br>
								<span><strong>Date: </strong> {{item.created_on}}</span><br>
								<span><strong>Status: </strong> {{item.status}}</span><br>
								<span><strong>Number of items:</strong> {{item.items_in_package_count}}</span><br>
								<span><strong>Destination:</strong> {{item.shipping_destination}}</span>
								<br>
								<span><strong>Tracking Number: </strong>{{item.tracking_number}}
								</span>
								<br>
								<span><strong>Shipping Status:</strong> {{item.shipping_status}}</span>
								<br>
								<span><strong>Payment Status:</strong> {{item.payment_status}}</span><br>
								<span><strong>Total:</strong> ${{item.total_amount}}</span><br>
							</div>
							<div class="col-md-4">			
								

									<a onclick='window.open("{% url 'general:package_invoice' item.tracking_number %}", "invoice", "width=800,height=700,scrollbars=yes,menubar=yes,status=yes,top=10,location=false")'  class="view-invoice" style="cursor:pointer;" ><i class="fa fa-file-text fa-3x" aria-hidden="true"></i>
									</a>
							</div>
							<div class="col-md-4">			
								
							</div>

						</div>
					</div>
					<div class="clearfix"></div>
					
					{% endfor %}
					<div class="pagination" style="position:relative; font-size:20px; margin:0px; left:500px;">
						<span class="step-links">

							{% if order_items.has_previous %}
								<a style="font-size:20px;" href="?page={{ order_items.previous_page_number }}">&laquo;</a>
							{% else %}
								<a style="font-size:20px;" class="hidden" >&laquo;</a>
							{% endif %}

							<span style="font-size:20px;" class="current">
								Page {{ order_items.number }} of {{ order_items.paginator.num_pages }}.
							</span>

							{% if order_items.has_next %}
								<a style="font-size:20px;" href="?page={{ order_items.next_page_number }}">&raquo;</a>
							{% else %}
								<a style="font-size:20px;" class="hidden">&raquo;</a>
							{% endif %}

						</span>
					</div>
				</div>	
			</div>
		</div>
		<hr>
	<!-- //new_arrivals --> 
	<!-- /we-offer -->
		
	<!-- //we-offer -->
<!--/grids-->

{% endblock inner_content %}

general/templates/general/cartBox.html
<div class="top_nav_right" id="cartBox">
	<div class="wthreecartaits wthreecartaits2 cart cart box_1"> 
		
		{% if request.user.is_authenticated %}	
		<a href="{% url 'general:view_cart' %}">
			<button class="w3view-cart" value="">
				<i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
			</button>
		</a>
		{% else %}
			<button class="w3view-cart emptyCart" value="">
				<i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
			</button>
		{% endif %}

		<input type="hidden" name="out_of_stock" value="{{out_of_stock}}">

		{% if request.user.is_authenticated %}{{items_in_cart}}{% endif %}	 
	</div>
</div>

general/templates/general/checkout.html
{% extends 'general/index.html' %}
{% load staticfiles %}
{% load humanize %}

{% block inner_content %}

	<!-- banner -->
	 
	<!-- //banner -->
    <!-- <div class="banner_bottom_agile_info">
	    <div class="container">
            <div class="banner_bottom_agile_info_inner_w3ls">
    	           <div class="col-md-6 wthree_banner_bottom_grid_three_left1 grid">
						<figure class="effect-roxy">
							<img src="{% static 'images/bottom1.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>
								<h3><span>F</span>all Ahead</h3>
								<p>New Arrivals</p>
							</figcaption>			
						</figure>
					</div>
					 <div class="col-md-6 wthree_banner_bottom_grid_three_left1 grid">
						<figure class="effect-roxy">
							<img src="{% static 'images/bottom2.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>
								<h3><span>F</span>all Ahead</h3>
								<p>New Arrivals</p>
							</figcaption>			
						</figure>
					</div>
					<div class="clearfix"></div>
		    </div> 
		 </div> 
    </div> -->
	<!-- schedule-bottom -->
	
	<!-- //schedule-bottom -->
  	<!-- banner-bootom-w3-agileits -->
	
<!-- /new_arrivals --> 
	<div class="new_arrivals_agile_w3ls_info">

		<div class="container">

			{% if not items_in_cart %}
		    <h3 class="wthree_text_info"><span>Your shopping cart is empty</span></h3>
		    {% else %}
		    <h3 class="wthree_text_info"><span>Shopping cart</span></h3>
		    {% endif %}		
				<div id="">				
					{% for item in order_items %}
					<div class="well">
						<div class="row">
							<div class="col-md-4">
								{% if item.item_image_big %}
                            	<span><img src="{{item.item_image.url}}" style="height: 120px;"></span>
                            	{% else %}
                                <span><img src="{% static 'images/default.jpg' %}" style="height: 120px;"></span>
                            	{% endif %}
							</div>
							<div class="col-md-4">		
								<span><strong>Name: </strong> {{item.name}}</span><br>
								<span><strong>Price: </strong> ${{item.price}}</span><br>
								<span><strong>Quantity:</strong> {{item.quantity}}</span><br>
								<span><strong>Status:</strong> {{item.status}}</span><br>
								<span><strong>Tracking Number: </strong>{{item.courier_tracking_number}}</span>
								<br>
								<span><strong>Total:</strong> ${{item.getTotal}}</span><br>
							</div>
							<div class="col-md-4">
								<a href="{% url 'general:remove_from_cart' item.pk %}" onclick="return confirm('Are you sure you want to remove this item from your shopping cart?')"><i class="fa fa-trash-o fa-3x pull-right" aria-hidden="true"></i></a>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
					
					{% endfor %}

					<div class="pagination" style="position:relative; font-size:20px; margin:0px; left:500px;">
						<span class="step-links">

							{% if order_items.has_previous %}
								<a style="font-size:20px;" href="?page={{ order_items.previous_page_number }}">&laquo;</a>
							{% else %}
								<a style="font-size:20px;" class="hidden" >&laquo;</a>
							{% endif %}

							<span style="font-size:20px;" class="current">
								Page {{ order_items.number }} of {{ order_items.paginator.num_pages }}.
							</span>

							{% if order_items.has_next %}
								<a style="font-size:20px;" href="?page={{ order_items.next_page_number }}">&raquo;</a>
							{% else %}
								<a style="font-size:20px;" class="hidden">&raquo;</a>
							{% endif %}

						</span>
					</div>

					{% if items_in_cart %}
					<span>
						<select id="shipping_to">
							<option value="" disabled selected>Select shipping destination</option>
							<option value="1">USA</option>
							<option value="2">Nigeria</option>
						</select>
						<input type="hidden" name="shipping_to" id="ship_to" value="">
						<button class="btn btn-primary pull-right" id="confirmOrder">Confirm Order</button>
					</span>
					{% endif %}
				</div>	
			</div>
		</div>
	<!-- //new_arrivals --> 
	<!-- /we-offer -->
		
	<!-- //we-offer -->
<!--/grids-->

{% endblock inner_content %}

general/templates/general/package_invoice_email_template.html
{% load humanize %}
{% load staticfiles %}

<html>
<body>
    <head>
        <!-- <link href="{% static 'sokohali/css/package_invoice.css' %}" rel="stylesheet"> -->
    </head>
<div style="font-size: larger;">
    <strong>
        Shopping Invoice: Package ID: {{ pkg.tracking_number }} <br/>
        <div style="color:green;">Status: {{pkg.status}}</style></div>
    </strong>
    </div>
    </p>
    <div>
        Thank you for shopping with <a href="http://wwww.look-fab.com">look-fab.com</a>.<br/><br/>

    </div>
    </p>

    
    <div>
        Please print and keep this document. It will be required at the point of collection of your package.<br/>
    </div>
    </p>
   
    </p>
    <table style="min-width: 600px;max-width: 600px;border-collapse: collapse;border: 2px solid black;padding:5px;">
        <tr>
            <td style="font-weight: bold;">What was shipped</td>
            <td style="font-weight: bold;">Qty.</td>
            <td style="font-weight: bold;">Price ($)</td>
        </tr>
            {% for item in pkg.items_in_package %}
                <tr>
                    <td style="border: 1px solid black; padding: 5px 10px;">{{item.name}}</td>
                    <td style="border: 1px solid black; padding: 5px 10px;">{{item.quantity}}</td>
                    <td style="border: 1px solid black; padding: 5px 10px;">{{item.getTotal|floatformat:2|intcomma}}</td>
                </tr>
            {% endfor %}
    </table>
    </p>
    <table class="table table-striped" style="min-width: 600px;max-width: 600px;border-collapse: collapse;border: 2px solid black;padding:5px;">
        <tr>
            <th style="font-weight: bold;">Total items cost ($)</th>
            <th style="font-weight: bold;">Total shipping cost ($)</th>
            <th style="font-weight: bold;">Grand Total ($)</th>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 5px 10px;"> {{ pkg.subTotal}}</td>
            <td style="border: 1px solid black; padding: 5px 10px;"> {{ pkg.shippingCost}}</td>
            <td style="border: 1px solid black; padding: 5px 10px;"> {{ pkg.total_amount}}</td>
        </tr>
    </table>
</body>
</html>